### ISSUE TITLE
TypeError: argument of type 'coroutine' is not iterable

### ISSUE THREAD

**Issue by kawaczek** [yshalsager/facebook2rss#10]
Hello,
I have the following problem.
```

root@e492:~/facebook2rss# python3 -m facebook_rss --login -u k***k@gmail.com -p O******U
/root/facebook2rss/facebook_rss/browser/common/login.py:39: RuntimeWarning: coroutine 'BasePage.get_actual_url' was never awaited
  return bool(self._checkout_url in self.get_actual_url())
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/facebook2rss/facebook_rss/__main__.py", line 23, in <module>
    asyncio.run(login_and_get_cookies(args.email, args.password))
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/root/facebook2rss/facebook_rss/tasks/login.py", line 21, in login_and_get_cookies
    if await login_page.requires_2fa:
  File "/root/facebook2rss/facebook_rss/browser/common/login.py", line 39, in requires_2fa
    return bool(self._checkout_url in self.get_actual_url())
TypeError: argument of type 'coroutine' is not iterable
root@e492:~/facebook2rss#

```

any ideas?

**Comment by yshalsager** [comment]
My bad! I forgot one word there..
Fixed in https://github.com/yshalsager/facebook2rss/commit/a6b6ba98472adcb8014fb6da61e07f90960ed3fe
Thanks for reporting! @kawaczek
